apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"respondr"},"name":"respondr-deployment","namespace":"respondr"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"respondr"}},"template":{"metadata":{"labels":{"app":"respondr","azure.workload.identity/use":"true"}},"spec":{"containers":[{"env":[{"name":"AZURE_OPENAI_API_KEY","valueFrom":{"secretKeyRef":{"key":"AZURE_OPENAI_API_KEY","name":"respondr-secrets"}}},{"name":"AZURE_OPENAI_ENDPOINT","valueFrom":{"secretKeyRef":{"key":"AZURE_OPENAI_ENDPOINT","name":"respondr-secrets"}}},{"name":"AZURE_OPENAI_DEPLOYMENT","valueFrom":{"secretKeyRef":{"key":"AZURE_OPENAI_DEPLOYMENT","name":"respondr-secrets"}}},{"name":"AZURE_OPENAI_API_VERSION","valueFrom":{"secretKeyRef":{"key":"AZURE_OPENAI_API_VERSION","name":"respondr-secrets"}}},{"name":"WEBHOOK_API_KEY","valueFrom":{"secretKeyRef":{"key":"WEBHOOK_API_KEY","name":"respondr-secrets"}}},{"name":"REDIS_HOST","value":"redis-service"},{"name":"REDIS_PORT","value":"6379"},{"name":"REDIS_DB","value":"0"}],"image":"respondrdqeunumstnsbmacr.azurecr.io/respondr:latest","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/api/responders","port":8000},"initialDelaySeconds":30,"periodSeconds":10},"name":"respondr","ports":[{"containerPort":8000}],"readinessProbe":{"httpGet":{"path":"/api/responders","port":8000},"initialDelaySeconds":5,"periodSeconds":5},"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"250m","memory":"256Mi"}}},{"args":["--provider=oidc","--provider-display-name=\"Microsoft Entra\"","--oidc-issuer-url=https://login.microsoftonline.com/d62aea99-b83c-45cb-919b-81127225d94a/v2.0","--redirect-url=https://respondr.paincave.pro/oauth2/callback","--email-domain=*","--upstream=http://localhost:8000","--http-address=0.0.0.0:4180","--cookie-secure=true","--cookie-httponly=true","--cookie-samesite=lax","--cookie-expire=24h","--skip-provider-button=true","--pass-access-token=true","--pass-user-headers=true","--set-xauthrequest=true","--silence-ping-logging=true","--skip-auth-regex=^/webhook$","--skip-auth-regex=^/health$","--whitelist-domain=respondr.paincave.pro"],"env":[{"name":"OAUTH2_PROXY_CLIENT_ID","valueFrom":{"secretKeyRef":{"key":"client-id","name":"oauth2-secrets"}}},{"name":"OAUTH2_PROXY_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"client-secret","name":"oauth2-secrets"}}},{"name":"OAUTH2_PROXY_COOKIE_SECRET","valueFrom":{"secretKeyRef":{"key":"cookie-secret","name":"oauth2-secrets"}}}],"image":"quay.io/oauth2-proxy/oauth2-proxy:v7.5.1","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/ping","port":4180},"initialDelaySeconds":10,"periodSeconds":10},"name":"oauth2-proxy","ports":[{"containerPort":4180}],"readinessProbe":{"httpGet":{"path":"/ping","port":4180},"initialDelaySeconds":5,"periodSeconds":5},"resources":{"limits":{"cpu":"100m","memory":"128Mi"},"requests":{"cpu":"50m","memory":"64Mi"}}}],"serviceAccountName":"respondr-sa"}}}}
  creationTimestamp: "2025-08-06T21:25:28Z"
  generation: 6
  labels:
    app: respondr
  name: respondr-deployment
  namespace: respondr
  resourceVersion: "37195"
  uid: d5af74c1-25e9-419d-84ed-6b0bf3d5571e
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: respondr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-08-06T15:03:18-07:00"
      creationTimestamp: null
      labels:
        app: respondr
        azure.workload.identity/use: "true"
    spec:
      containers:
      - env:
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: AZURE_OPENAI_API_KEY
              name: respondr-secrets
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: AZURE_OPENAI_ENDPOINT
              name: respondr-secrets
        - name: AZURE_OPENAI_DEPLOYMENT
          valueFrom:
            secretKeyRef:
              key: AZURE_OPENAI_DEPLOYMENT
              name: respondr-secrets
        - name: AZURE_OPENAI_API_VERSION
          valueFrom:
            secretKeyRef:
              key: AZURE_OPENAI_API_VERSION
              name: respondr-secrets
        - name: WEBHOOK_API_KEY
          valueFrom:
            secretKeyRef:
              key: WEBHOOK_API_KEY
              name: respondr-secrets
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        image: respondrdqeunumstnsbmacr.azurecr.io/respondr:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/responders
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: respondr
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/responders
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --provider=oidc
        - --provider-display-name="Microsoft Entra"
        - --oidc-issuer-url=https://login.microsoftonline.com/d62aea99-b83c-45cb-919b-81127225d94a/v2.0
        - --redirect-url=https://respondr.paincave.pro/oauth2/callback
        - --email-domain=*
        - --upstream=http://localhost:8000
        - --http-address=0.0.0.0:4180
        - --cookie-secure=true
        - --cookie-httponly=true
        - --cookie-samesite=lax
        - --cookie-expire=24h
        - --skip-provider-button=true
        - --pass-access-token=true
        - --pass-user-headers=true
        - --set-xauthrequest=true
        - --silence-ping-logging=true
        - --skip-auth-regex=^/webhook$
        - --skip-auth-regex=^/health$
        - --whitelist-domain=respondr.paincave.pro
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: oauth2-secrets
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: oauth2-secrets
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie-secret
              name: oauth2-secrets
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 4180
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 4180
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: respondr-sa
      serviceAccountName: respondr-sa
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-08-06T21:25:52Z"
    lastUpdateTime: "2025-08-06T21:25:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-06T21:25:28Z"
    lastUpdateTime: "2025-08-06T23:05:57Z"
    message: ReplicaSet "respondr-deployment-848596ccf4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
