apiVersion: apps/v1
kind: Deployment
metadata:
  name: respondr-deployment
  namespace: respondr
  labels:
    app: respondr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: respondr
  template:
    metadata:
      labels:
        app: respondr
        azure.workload.identity/use: "true"  # Required for workload identity
    spec:
      serviceAccountName: respondr-sa
      containers:
      - name: respondr
        image: {{ACR_IMAGE_PLACEHOLDER}}
        ports:
        - containerPort: 8000
        env:
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: respondr-secrets
              key: AZURE_OPENAI_API_KEY
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: respondr-secrets
              key: AZURE_OPENAI_ENDPOINT
        - name: AZURE_OPENAI_DEPLOYMENT
          valueFrom:
            secretKeyRef:
              name: respondr-secrets
              key: AZURE_OPENAI_DEPLOYMENT
        - name: AZURE_OPENAI_API_VERSION
          valueFrom:
            secretKeyRef:
              name: respondr-secrets
              key: AZURE_OPENAI_API_VERSION
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/responders
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/responders
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: respondr-sa
  namespace: respondr
  annotations:
    azure.workload.identity/client-id: CLIENT_ID_PLACEHOLDER
    azure.workload.identity/tenant-id: TENANT_ID_PLACEHOLDER

---
apiVersion: v1
kind: Service
metadata:
  name: respondr-service
  namespace: respondr
  labels:
    app: respondr
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: respondr

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: respondr-ingress
  namespace: respondr
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/auth-setting: respondrAuth  # Reference to the auth-setting created in post-deploy
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
    - HOSTNAME_PLACEHOLDER
    secretName: respondr-tls-letsencrypt
  rules:
  - host: HOSTNAME_PLACEHOLDER
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: respondr-service
            port:
              number: 80
