apiVersion: apps/v1
kind: Deployment
metadata:
  name: respondr-deployment
  namespace: respondr
  labels:
    app: respondr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: respondr
  template:
    metadata:
      labels:
        app: respondr
        azure.workload.identity/use: "true"  # Required for workload identity
    spec:
      serviceAccountName: respondr-sa
      containers:
      # Main application container
      - name: respondr
        image: {{ACR_IMAGE_PLACEHOLDER}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ACR_WEBHOOK_TOKEN
          valueFrom:
            secretKeyRef:
              name: respondr-secrets
              key: ACR_WEBHOOK_TOKEN
        - name: K8S_NAMESPACE
          value: respondr
        - name: K8S_DEPLOYMENT
          value: respondr-deployment
        - name: ACR_REPOSITORY
          value: respondr
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: respondr-secrets
              key: AZURE_OPENAI_API_KEY
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: respondr-secrets
              key: AZURE_OPENAI_ENDPOINT
        - name: AZURE_OPENAI_DEPLOYMENT
          valueFrom:
            secretKeyRef:
              name: respondr-secrets
              key: AZURE_OPENAI_DEPLOYMENT
        - name: AZURE_OPENAI_API_VERSION
          valueFrom:
            secretKeyRef:
              name: respondr-secrets
              key: AZURE_OPENAI_API_VERSION
        - name: WEBHOOK_API_KEY
          valueFrom:
            secretKeyRef:
              name: respondr-secrets
              key: WEBHOOK_API_KEY
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: ALLOWED_EMAIL_DOMAINS
          value: {{ALLOWED_EMAIL_DOMAINS_PLACEHOLDER}}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/responders
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/responders
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
  # (imagePullPolicy set per-container above)

      # OAuth2 Proxy sidecar container (conditional - will be removed if ENABLE_OAUTH2=false)
      {{OAUTH2_CONTAINER_START}}- name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
        ports:
        - containerPort: 4180
        args:
        - --provider=oidc
        - --provider-display-name="Microsoft Entra"
        - --oidc-issuer-url=https://login.microsoftonline.com/{{OIDC_TENANT_SEGMENT}}/v2.0
        - --redirect-url={{REDIRECT_URL_PLACEHOLDER}}
        - --insecure-oidc-skip-issuer-verification=true
{{EMAIL_DOMAIN_ARGS}}
        - --upstream=http://localhost:8000
        - --http-address=0.0.0.0:4180
        - --cookie-secure=true
        - --cookie-httponly=true
        - --cookie-samesite=lax
        - --cookie-expire=24h
        - --skip-provider-button=true
        - --pass-access-token=true
        - --pass-user-headers=true
        - --set-xauthrequest=true
        - --silence-ping-logging=true
        - --skip-auth-regex=^/webhook$
        - --skip-auth-regex=^/health$
        - --skip-auth-regex=^/internal/acr-webhook$
        - --whitelist-domain={{HOSTNAME_PLACEHOLDER}}
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-secrets
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-secrets
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-secrets
              key: cookie-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: IfNotPresent
      {{OAUTH2_CONTAINER_END}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: respondr-sa
  namespace: respondr
  annotations:
    azure.workload.identity/client-id: {{CLIENT_ID_PLACEHOLDER}}
    azure.workload.identity/tenant-id: {{TENANT_ID_PLACEHOLDER}}

---
apiVersion: v1
kind: Service
metadata:
  name: respondr-service
  namespace: respondr
  labels:
    app: respondr
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  ports:
  # Port configuration changes based on OAuth2 mode
  {{SERVICE_PORT_CONFIG}}
  selector:
    app: respondr

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: respondr-deployment-manager
  namespace: respondr
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: respondr-deployment-manager-binding
  namespace: respondr
subjects:
- kind: ServiceAccount
  name: respondr-sa
  namespace: respondr
roleRef:
  kind: Role
  name: respondr-deployment-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: respondr-ingress
  namespace: respondr
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    # Session affinity for Application Gateway
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
spec:
  tls:
  - hosts:
    - {{HOSTNAME_PLACEHOLDER}}
    secretName: respondr-tls-letsencrypt
  rules:
  - host: {{HOSTNAME_PLACEHOLDER}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: respondr-service
            port:
              number: 80
