apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}-deployment
  namespace: {{NAMESPACE_PLACEHOLDER}}
  labels:
    app: {{APP_NAME}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
        azure.workload.identity/use: "true"  # Required for workload identity
    spec:
      serviceAccountName: {{APP_NAME}}-sa
      containers:
      # Main application container
      - name: {{APP_NAME}}
        image: {{ACR_IMAGE_PLACEHOLDER}}
        ports:
        - containerPort: 8000
        env:
        - name: ACR_WEBHOOK_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{APP_NAME}}-secrets
              key: ACR_WEBHOOK_TOKEN
        - name: K8S_NAMESPACE
          value: {{NAMESPACE_PLACEHOLDER}}
        - name: K8S_DEPLOYMENT
          value: {{APP_NAME}}-deployment
        - name: ACR_REPOSITORY
          value: {{APP_NAME}}
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{APP_NAME}}-secrets
              key: AZURE_OPENAI_API_KEY
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{APP_NAME}}-secrets
              key: AZURE_OPENAI_ENDPOINT
        - name: AZURE_OPENAI_DEPLOYMENT
          valueFrom:
            secretKeyRef:
              name: {{APP_NAME}}-secrets
              key: AZURE_OPENAI_DEPLOYMENT
        - name: AZURE_OPENAI_API_VERSION
          valueFrom:
            secretKeyRef:
              name: {{APP_NAME}}-secrets
              key: AZURE_OPENAI_API_VERSION
        - name: WEBHOOK_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{APP_NAME}}-secrets
              key: WEBHOOK_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
  imagePullPolicy: Always

      # OAuth2 Proxy sidecar container (conditional - will be removed if ENABLE_OAUTH2=false)
      {{OAUTH2_CONTAINER_START}}- name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
        ports:
        - containerPort: 4180
        args:
        - --provider=oidc
        - --provider-display-name="Microsoft Entra"
        - --oidc-issuer-url=https://login.microsoftonline.com/{{OIDC_TENANT_SEGMENT}}/v2.0
        - --redirect-url=https://{{HOSTNAME_PLACEHOLDER}}/oauth2/callback
{{EMAIL_DOMAIN_ARGS}}
        - --upstream=http://localhost:8000
        - --http-address=0.0.0.0:4180
        - --cookie-secure=true
        - --cookie-httponly=true
        - --cookie-samesite=lax
        - --cookie-expire=24h
        - --skip-provider-button=true
        - --pass-access-token=true
        - --pass-user-headers=true
        - --set-xauthrequest=true
        - --silence-ping-logging=true
  - --skip-auth-regex=^/webhook$
  - --skip-auth-regex=^/health$
  - --skip-auth-regex=^/internal/acr-webhook$
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-secrets
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-secrets
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-secrets
              key: cookie-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: IfNotPresent
{{OAUTH2_CONTAINER_END}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{APP_NAME}}-sa
  namespace: {{NAMESPACE_PLACEHOLDER}}
  annotations:
    azure.workload.identity/client-id: {{CLIENT_ID_PLACEHOLDER}}
    azure.workload.identity/tenant-id: {{TENANT_ID_PLACEHOLDER}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-service
  namespace: {{NAMESPACE_PLACEHOLDER}}
  labels:
    app: {{APP_NAME}}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  ports:
  # Port configuration changes based on OAuth2 mode
  {{SERVICE_PORT_CONFIG}}
  selector:
  app: {{APP_NAME}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{APP_NAME}}-deployment-manager
  namespace: {{NAMESPACE_PLACEHOLDER}}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{APP_NAME}}-deployment-manager-binding
  namespace: {{NAMESPACE_PLACEHOLDER}}
subjects:
- kind: ServiceAccount
  name: {{APP_NAME}}-sa
  namespace: {{NAMESPACE_PLACEHOLDER}}
roleRef:
  kind: Role
  name: {{APP_NAME}}-deployment-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{APP_NAME}}-ingress
  namespace: {{NAMESPACE_PLACEHOLDER}}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    # Session affinity for Application Gateway
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
spec:
  tls:
  - hosts:
    - {{HOSTNAME_PLACEHOLDER}}
    - respondr.scvsar.app
    secretName: {{APP_NAME}}-tls-letsencrypt
  rules:
  - host: {{HOSTNAME_PLACEHOLDER}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{APP_NAME}}-service
            port:
              number: 80
  - host: respondr.scvsar.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{APP_NAME}}-service
            port:
              number: 80